### ISSUE TITLE
Remove dependency on `extra`?

### ISSUE THREAD

**Issue by tfausak** [ndmitchell/filepattern#7]
It would be nice if `filepattern` only depended on boot libraries. Is there an appetite for removing the dependency on `extra`? I think all the places it's used can be replaced with non-`extra` functions or inlined.

**Comment by ndmitchell** [comment]
What's the desire? If you are in a domain where Cabal is available it seems like an irrelevance? Or are you aiming for a different domain? You can pretty much always inline everything from another library, but that leads to duplication and potentially bugs.

**Comment by tfausak** [comment]
Just a pathological desire to avoid dependencies. No worries!
